name: Bundle into a single file
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun run build
      - uses: actions/upload-artifact@v4
        with:
          path: dist/sol.js
