name: Bundle into a single file
on:
  push:
    paths:
      - "*.ts"
      - "package.json"
      - "bun.lock"
      - ".github/worklows/build.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
      - run: bun install
        name: Install dependencies
      - run: bun run build
        name: Bundle
      - uses: actions/upload-artifact@v4
        name: Upload sol.js
        with:
          name: sol.js
          path: dist/sol.js
